# Generated by Django 5.2.9 on 2025-12-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_era', '0003_audioupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_file', models.FileField(upload_to='signal_uploads/')),
                ('spectrum_summary', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
