# Generated by Django 5.2.9 on 2025-12-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_era', '0004_signalupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='text_uploads/')),
                ('input_text', models.TextField(blank=True)),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
